-- CREATE TABLE product_images (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     product_id BIGINT NOT NULL,
--     image_url VARCHAR(500) NOT NULL,
--     FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
-- );
